### ISSUE TITLE
Кирилл А.

### ISSUE THREAD

**Issue by UsernameMi** [ing-prog/cpp_2019_1_g2#2]
https://onlinegdb.com/S1TogO-DV - НОД
https://onlinegdb.com/HJQ34uZPV - квадратное уравнение

**Comment by vlasove** [comment]
По НОДу: ожидается, что НОД (0,15)  = 15, у тебя ответ в этом случае отсутствует совсем

**Comment by vlasove** [comment]
Для чего тебе ` <stdio.h> `  в задаче?

**Comment by vlasove** [comment]
Ввод в уравнение (0,0,1) при водит к неожиданному ответу. В случае отсутствия корней должен быть пустой вывод.

Ввод (0,1,0) тоже выдает ошибочный результат, хотя ответ здесь очевиден и он вполне себе вещественное число.

**Comment by UsernameMi** [comment]
Забыл убрать строку, когда пользовался онлайн компилятором.
--
Отправлено из Mail.Ru для Android вторник, 26 марта 2019г., 16:45 +03:00 от Evgeny Vlasov  notifications@github.com :

**Comment by UsernameMi** [comment]
https://www.onlinegdb.com/fork/S1TogO-DV - исправленный НОД
