### ISSUE TITLE
Куликов В.

### ISSUE THREAD

**Issue by IdentityVladimir** [ing-prog/cpp_2019_1_g2#3]
[1.txt](https://github.com/ing-prog/cpp_2019_1_g2/files/2957545/1.txt)
[2.txt](https://github.com/ing-prog/cpp_2019_1_g2/files/2957546/2.txt)

**Comment by vlasove** [comment]
Зачем txt? Может лучше будет скинуть сразу .cpp файлы?

**Comment by vlasove** [comment]
Палиндром работает ОК, но есть вопрос.
Для чего тебе ` <string> ` в этой задаче?

**Comment by vlasove** [comment]
Где в задаче с корнями тело main? Не вижу либы ` cmath `, но вижу функцию из нее ` sqrt `
