### ISSUE TITLE
HW 26.03 Карсанов Тамерлан

### ISSUE THREAD

**Issue by Jashu9an** [ing-prog/cpp_2019_1_g2#5]
https://onlinegdb.com/HkUVZnnuV  -   подстрока в строке
https://www.onlinegdb.com/SJa0D33uV#   - почти-палиндромы
@vlasove

**Comment by vlasove** [comment]
Супер! Только не забывай меня в  assigne кидать) + заведи себе гит и заливай на него - не пуш с гдб
